// integration-validation/react/foundation/NavStateExample.jsx
import React, { useState } from 'react';

export default function NavStateExample() {
    const [isOpen, setIsOpen] = useState(false);
    const [activeTab, setActiveTab] = useState('Dashboard');

    const menuItems = ['Dashboard', 'Reports', 'Users', 'Settings'];

    return (
        /* Stateful top-bar navigation demonstrating Foundation's header menu responsive bindings */
        <nav className="top-bar-container">
            {/* Mobile Title Bar */}
            <div className="title-bar" style={{ display: 'flex', justifyContent: 'space-between', padding: '0.5rem' }}>
                <span className="title-bar-title font-bold text-white">AdminPanel X</span>
                <button 
                    className="menu-icon dark border-0 bg-transparent" 
                    type="button" 
                    onClick={() => setIsOpen(!isOpen)}
                    aria-label="Toggle menu"
                ></button>
            </div>
            {/* Responsive Menu Area */}
            <div className={`top-bar ${isOpen ? 'show-menu' : ''}`} style={{ display: isOpen ? 'block' : 'none' }}>
                <div className="top-bar-left">
                    <ul className="menu vertical medium-horizontal">
                        <li className="menu-text hide-for-small-only">AdminPanel X</li>
                        {menuItems.map(item => (
                            <li key={item} className={activeTab === item ? 'active' : ''}>
                                <button
                                    onClick={() => {
                                        setActiveTab(item);
                                        setIsOpen(false);
                                    }}
                                    className="button clear margin-0"
                                >
                                    {item}
                                </button>
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="top-bar-right">
                    <ul className="menu vertical medium-horizontal">
                        <li>
                            <button type="button" className="button">
                                Create New
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    );
}

// integration-validation/vue/foundation/NavStateExample.vue
<template>
  <!-- Stateful top-bar navigation template showing Foundation's responsive menu components and classes -->
  <nav class="top-bar-container">
    <!-- Mobile Title Bar -->
    <div class="title-bar" style="display: flex; justify-content: space-between; padding: 0.5rem;">
      <span class="title-bar-title font-bold text-white">AdminPanel X</span>
      <button 
        class="menu-icon dark border-0 bg-transparent" 
        type="button" 
        @click="isOpen = !isOpen"
        aria-label="Toggle menu"
      ></button>
    </div>
    <!-- Responsive Menu Area -->
    <div class="top-bar" :class="{ 'show-menu': isOpen }" :style="{ display: isOpen ? 'block' : 'none' }">
      <div class="top-bar-left">
        <ul class="menu vertical medium-horizontal">
          <li class="menu-text hide-for-small-only">AdminPanel X</li>
          <li v-for="item in menuItems" :key="item" :class="{ active: activeTab === item }">
            <button
              @click="activeTab = item; isOpen = false"
              class="button clear margin-0"
            >
              {{ item }}
            </button>
          </li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu vertical medium-horizontal">
          <li>
            <button type="button" class="button">
              Create New
            </button>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { ref } from 'vue';

const isOpen = ref(false);
const activeTab = ref('Dashboard');

const menuItems = ['Dashboard', 'Reports', 'Users', 'Settings'];
</script>
