// integration-validation/vue/bulma/FormInput.vue
<template>
  <!-- Form control field built with Bulma's semantic wrapper element classes -->
  <div class="field">
    <label for="fullname" class="label">
      Full Name
    </label>
    <div class="control">
      <input 
        type="text" 
        id="fullname" 
        placeholder="Enter full name" 
        class="input"
      />
    </div>
  </div>
</template>

<script setup>
</script>

// integration-validation/angular/bulma/form-input.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-form-input',
  standalone: true,
  templateUrl: './form-input.component.html'
})
export class FormInputComponent {}

<!-- Form control field built with Bulma's semantic wrapper element classes -->
<div class="field">
    <label for="fullname" class="label">
        Full Name
    </label>
    <div class="control">
        <input 
            type="text" 
            id="fullname" 
            placeholder="Enter full name" 
            class="input"
        />
    </div>
</div>
