// integration-validation/angular/bootstrap/button-group.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-button-group',
  standalone: true,
  templateUrl: './button-group.component.html'
})
export class ButtonGroupComponent {}

<!-- Button layout spacing utilizing Bootstrap 5 d-flex and gap utility classes -->
<div class="d-flex gap-2">
    <button type="submit" class="btn btn-primary">
        Submit
    </button>
    <button type="button" class="btn btn-secondary">
        Cancel
    </button>
</div>

// integration-validation/vue/bootstrap/ButtonGroup.vue
<template>
  <!-- Button layout spacing utilizing Bootstrap 5 d-flex and gap utility classes -->
  <div class="d-flex gap-2">
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
    <button type="button" class="btn btn-secondary">
      Cancel
    </button>
  </div>
</template>

<script setup>
</script>
