// integration-validation/react/bootstrap/SummaryCard.jsx
import React from 'react';

export default function SummaryCard() {
    return (
        /* Bootstrap 5 card component representing metrics summary card */
        <div className="card shadow-sm">
            <div className="card-body">
                <dl className="mb-0">
                    <dt className="text-secondary small fw-medium mb-1 text-truncate">Active Users</dt>
                    <dd className="fs-3 fw-semibold text-dark mb-0">1,248</dd>
                </dl>
            </div>
        </div>
    );
}

// integration-validation/vue/bootstrap/SummaryCard.vue
<template>
  <!-- Bootstrap 5 card component representing metrics summary card -->
  <div class="card shadow-sm">
    <div class="card-body">
      <dl class="mb-0">
        <dt class="text-secondary small fw-medium mb-1 text-truncate">Active Users</dt>
        <dd class="fs-3 fw-semibold text-dark mb-0">1,248</dd>
      </dl>
    </div>
  </div>
</template>

<script setup>
</script>
