// integration-validation/vue/bootstrap/NavStateExample.vue
<template>
  <!-- Stateful header navigation showing Bootstrap 5 navbar components and active styles -->
  <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
    <div class="container-fluid">
      <span class="navbar-brand fw-bold">AdminPanel X</span>
      <!-- Mobile Hamburger Trigger -->
      <button 
        class="navbar-toggler" 
        type="button" 
        @click="isOpen = !isOpen"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Responsive Menu Collapse Container -->
      <div class="collapse navbar-collapse" :class="{ show: isOpen }">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li v-for="item in menuItems" :key="item" class="nav-item">
            <button
              @click="activeTab = item; isOpen = false"
              class="nav-link border-0 bg-transparent"
              :class="{ active: activeTab === item, 'fw-semibold text-primary': activeTab === item, 'text-secondary': activeTab !== item }"
            >
              {{ item }}
            </button>
          </li>
        </ul>
        <div class="d-flex">
          <button type="button" class="btn btn-primary">
            Create New
          </button>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { ref } from 'vue';

const isOpen = ref(false);
const activeTab = ref('Dashboard');

const menuItems = ['Dashboard', 'Reports', 'Users', 'Settings'];
</script>

// integration-validation/react/bootstrap/NavStateExample.jsx
import React, { useState } from 'react';

export default function NavStateExample() {
    const [isOpen, setIsOpen] = useState(false);
    const [activeTab, setActiveTab] = useState('Dashboard');

    const menuItems = ['Dashboard', 'Reports', 'Users', 'Settings'];

    return (
        /* Stateful header navigation demonstrating Bootstrap 5 responsive collapse bindings */
        <nav className="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div className="container-fluid">
                <span className="navbar-brand fw-bold">AdminPanel X</span>
                {/* Mobile Hamburger Drawer Trigger */}
                <button 
                    className="navbar-toggler" 
                    type="button" 
                    onClick={() => setIsOpen(!isOpen)}
                    aria-label="Toggle navigation"
                >
                    <span className="navbar-toggler-icon"></span>
                </button>
                {/* Responsive Menu Collapse Container */}
                <div className={`collapse navbar-collapse ${isOpen ? 'show' : ''}`} id="navbarNav">
                    <ul className="navbar-nav me-auto mb-2 mb-md-0">
                        {menuItems.map(item => (
                            <li key={item} className="nav-item">
                                <button
                                    onClick={() => {
                                        setActiveTab(item);
                                        setIsOpen(false);
                                    }}
                                    /* Dynamic conditional class definitions for active tab state */
                                    className={`nav-link border-0 bg-transparent ${
                                        activeTab === item ? 'active fw-semibold text-primary' : 'text-secondary'
                                    }`}
                                >
                                    {item}
                                </button>
                            </li>
                        ))}
                    </ul>
                    <div className="d-flex">
                        <button type="button" className="btn btn-primary">
                            Create New
                        </button>
                    </div>
                </div>
            </div>
        </nav>
    );
}
