// integration-validation/vue/foundation/ButtonGroup.vue
<template>
  <!-- Dynamic action button overrides using Foundation's built-in button-group classes -->
  <div class="button-group">
    <button type="submit" class="button">
      Submit
    </button>
    <button type="button" class="button secondary">
      Cancel
    </button>
  </div>
</template>

<script setup>
</script>

// integration-validation/react/foundation/ButtonGroup.jsx
import React from 'react';

export default function ButtonGroup() {
    return (
        /* Dynamic action button overrides using Foundation's built-in button-group classes */
        <div className="button-group">
            <button type="submit" className="button">
                Submit
            </button>
            <button type="button" className="button secondary">
                Cancel
            </button>
        </div>
    );
}
